//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TamagotchiBot.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Again.
        /// </summary>
        public static string againText {
            get {
                return ResourceManager.GetString("againText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules of the game are simple: the one who eats an unripe green apple will lose.
        ///You can choose to eat one 🍎, two 🍎🍎 or three 🍎🍎🍎 apples at a time
        ///Can you outplay your pet and leave him a tasteless 🍏?.
        /// </summary>
        public static string appleGameHelpText {
            get {
                return ResourceManager.GetString("appleGameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your green apple remains
        ///
        ///🐱: Better luck next time 😉.
        /// </summary>
        public static string appleGameLoseText {
            get {
                return ResourceManager.GetString("appleGameLoseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📈STATISTICS📉
        ///Won: {0}
        ///Lost: {1}
        ///Surrendered: {2}.
        /// </summary>
        public static string appleGameStatisticsCommand {
            get {
                return ResourceManager.GetString("appleGameStatisticsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱: I ate apples - {0}.
        /// </summary>
        public static string appleGameSysEaten {
            get {
                return ResourceManager.GetString("appleGameSysEaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one 🍎, two 🍎🍎 or three 🍎🍎🍎 apples to eat.
        /// </summary>
        public static string appleGameUndefiendText {
            get {
                return ResourceManager.GetString("appleGameUndefiendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱: You won, well done!.
        /// </summary>
        public static string appleGameWinText {
            get {
                return ResourceManager.GetString("appleGameWinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change your pet&apos;s name from {0} to {1}? 🗃
        ///Price: {2} gold 💰.
        /// </summary>
        public static string AskToConfirmRenamingPet {
            get {
                return ResourceManager.GetString("AskToConfirmRenamingPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the gameroom ⚽️.
        /// </summary>
        public static string backToGameroomText {
            get {
                return ResourceManager.GetString("backToGameroomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet doesn&apos;t like his new name 😾
        ///Suggest something else ⬇️.
        /// </summary>
        public static string BadWordDetected {
            get {
                return ResourceManager.GetString("BadWordDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in the bathroom 🛁
        ///🚿 Hygiene: {0}%
        ///
        ///Remember to brush your teeth before going to bed🪥.
        /// </summary>
        public static string bathroomCommand {
            get {
                return ResourceManager.GetString("bathroomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🪥 Brush teeth.
        /// </summary>
        public static string bathroomCommandBrushTeeth {
            get {
                return ResourceManager.GetString("bathroomCommandBrushTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom 🛁.
        /// </summary>
        public static string bathroomCommandDescription {
            get {
                return ResourceManager.GetString("bathroomCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛁Shower.
        /// </summary>
        public static string bathroomCommandTakeShower {
            get {
                return ResourceManager.GetString("bathroomCommandTakeShower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new language:
        ///- Belarusian (беларуская) 🇨🇷
        ///- Russian (русский) 🇷🇺
        ///- English 🇺🇸
        ///- Polish (Polski) 🇵🇱.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡️⚡️ Update 1.3 has been released⚡️⚡️
        ///
        ///Added:
        ///👨‍👦‍👦Multiplayer - the bot can already be added to the group chat!
        ///Now you can show off your pet to your friends 😈
        ///🥂New random pet-related events
        ///🦥Referral program - you invite friends and get bonuses for it 💰 (command /referal)
        ///🧩The /changelog command has been added - here is a link to a channel about our Tamagotchi bot, where you can discuss the latest updates and suggest something new
        ///
        ///Corrections:
        ///🐛 The keyboard was often not hidden after  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string changelog1Text {
            get {
                return ResourceManager.GetString("changelog1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📢💬 You can view and discuss bot updates here:
        ///{0}.
        /// </summary>
        public static string changelogCommand {
            get {
                return ResourceManager.GetString("changelogCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📲 Updates.
        /// </summary>
        public static string changelogCommandDescription {
            get {
                return ResourceManager.GetString("changelogCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗳 Channel with updates.
        /// </summary>
        public static string ChangelogGoToDicussChannelButton {
            get {
                return ResourceManager.GetString("ChangelogGoToDicussChannelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧸 First of all you need to name your new friend
        ///Just type it here.
        /// </summary>
        public static string ChooseName {
            get {
                return ResourceManager.GetString("ChooseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concede.
        /// </summary>
        public static string ConcedeText {
            get {
                return ResourceManager.GetString("ConcedeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language was set to English 🇺🇸.
        /// </summary>
        public static string ConfirmedLanguage {
            get {
                return ResourceManager.GetString("ConfirmedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧃 Nice!
        ///Your pet {0} is waiting for you 🐱
        ///Do not forget feed and wash him, play the games and just love ☺️
        ///
        ///BTW &apos;/menu&apos; shows some commands to start.
        /// </summary>
        public static string ConfirmedName {
            get {
                return ResourceManager.GetString("ConfirmedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active 🌞.
        /// </summary>
        public static string CurrentStatusActive {
            get {
                return ResourceManager.GetString("CurrentStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleeping 🌙.
        /// </summary>
        public static string CurrentStatusSleeping {
            get {
                return ResourceManager.GetString("CurrentStatusSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on work 💻.
        /// </summary>
        public static string CurrentStatusWorkingOnPC {
            get {
                return ResourceManager.GetString("CurrentStatusWorkingOnPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you got +{0} gold! 🎈.
        /// </summary>
        public static string DailyRewardAnwserCallback {
            get {
                return ResourceManager.GetString("DailyRewardAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not come in: pet is sleeping 🌙.
        /// </summary>
        public static string denyAccessSleeping {
            get {
                return ResourceManager.GetString("denyAccessSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not come in: pet is on work 💻.
        /// </summary>
        public static string denyAccessWorking {
            get {
                return ResourceManager.GetString("denyAccessWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In developing, wait for next update 👾.
        /// </summary>
        public static string DevelopWarning {
            get {
                return ResourceManager.GetString("DevelopWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚔️Accept the challenge.
        /// </summary>
        public static string DuelMPAcceptButton {
            get {
                return ResourceManager.GetString("DuelMPAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}, Your pet is resting after losing the last duel🥷
        ///Just wait {0}.
        /// </summary>
        public static string DuelMPCooldown {
            get {
                return ResourceManager.GetString("DuelMPCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet is resting after losing the last duel🥷
        ///It remains to wait {0}.
        /// </summary>
        public static string DuelMPCooldownCallback {
            get {
                return ResourceManager.GetString("DuelMPCooldownCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t accept your own duels 🙈.
        /// </summary>
        public static string DuelMPErrorYourself {
            get {
                return ResourceManager.GetString("DuelMPErrorYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔰THE DUEL HAS BEGAN🔰
        ///{0} ⚔️ {1}
        ///--------------------------------
        ///
        ///{2} 🙀🛡          🗡😼{3}.
        /// </summary>
        public static string DuelMPFighting1 {
            get {
                return ResourceManager.GetString("DuelMPFighting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔰THE DUEL HAS BEGAN🔰
        ///{0} ⚔️ {1}
        ///--------------------------------
        ///
        ///{2} 🙀🛡        🗡😼{3}
        ///
        ///❕Pet {3} started attacking {2}!.
        /// </summary>
        public static string DuelMPFighting2 {
            get {
                return ResourceManager.GetString("DuelMPFighting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔰THE DUEL HAS BEGAN🔰
        ///{0} ⚔️ {1}
        ///--------------------------------
        ///
        ///{2} 🙀🛡     🗡😼{3}
        ///
        ///‼️Pet {3} is already very close to {2}!.
        /// </summary>
        public static string DuelMPFighting3 {
            get {
                return ResourceManager.GetString("DuelMPFighting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔰THE DUEL HAS BEGAN🔰
        ///{0} ⚔️ {1}
        ///--------------------------------
        ///
        ///{2} 🙀🛡  🗡😼{3}
        ///
        ///💥Pet {3} hits {2}....
        /// </summary>
        public static string DuelMPFighting4 {
            get {
                return ResourceManager.GetString("DuelMPFighting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎌&lt;b&gt;THE DUEL IS OVER&lt;/b&gt;🎌
        ///{0} ⚔️ {1}
        ///🏆&lt;b&gt;VICTORY&lt;/b&gt; {2}🏆
        ///--------------------------------
        ///
        ///{3}
        ///&lt;b&gt;Reward: {4}&lt;/b&gt;💰.
        /// </summary>
        public static string DuelMPFightingEnd {
            get {
                return ResourceManager.GetString("DuelMPFightingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet {1} hits the shield with lightning speed💢
        ///{0} got scared and asked to stop the duel🙅‍♂️
        ///😽{1} wins 🥇.
        /// </summary>
        public static string DuelMPFightingEndingAttackerWin {
            get {
                return ResourceManager.GetString("DuelMPFightingEndingAttackerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet {1} slipped and fell on his butt during an attack🧸
        ///😽{0} wins 🥇.
        /// </summary>
        public static string DuelMPFightingEndingDefenderWin {
            get {
                return ResourceManager.GetString("DuelMPFightingEndingDefenderWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♨️{0} announces a pet duel!♨️
        ///&quot;My {1}😼 kicks ass and takes names! Who will challenge us?!&quot;.
        /// </summary>
        public static string DuelMPStartCommand {
            get {
                return ResourceManager.GetString("DuelMPStartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one accepted the duel from {0}
        ///&lt;i&gt;So everyone is afraid of pet {1}&lt;/i&gt; 🌚
        ///
        ///The contribution in the amount of {2}💰 was returned to the account.
        /// </summary>
        public static string DuelMPTimeout {
            get {
                return ResourceManager.GetString("DuelMPTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It happens to everyone, but life goes on!
        ///Maybe you&apos;ll be lucky with a new pet 😼
        ///Try again? 🫶.
        /// </summary>
        public static string EpilogueText {
            get {
                return ResourceManager.GetString("EpilogueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have come to {0}, but all you see is an empty room and a note on the table:
        ///&quot;My beloved friend {1}!
        ///It was very nice to spend time with you, but I&apos;ve started feel not good.
        ///You should have kept an eye on me...😿&quot;
        ///
        ///Your pet left because he lacked care 💔.
        /// </summary>
        public static string FarewellText {
            get {
                return ResourceManager.GetString("FarewellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fresh.
        /// </summary>
        public static string FatigueFresh {
            get {
                return ResourceManager.GetString("FatigueFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rested.
        /// </summary>
        public static string FatigueRested {
            get {
                return ResourceManager.GetString("FatigueRested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleepy.
        /// </summary>
        public static string FatigueSleepy {
            get {
                return ResourceManager.GetString("FatigueSleepy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slightly tired.
        /// </summary>
        public static string FatigueSlightlyTired {
            get {
                return ResourceManager.GetString("FatigueSlightlyTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tired.
        /// </summary>
        public static string FatigueTired {
            get {
                return ResourceManager.GetString("FatigueTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the gameroom
        ///
        ///⚽️ Fatigue: {0}%
        ///🎊 Joy: {1}%
        ///💰 Gold: {2} 
        ///
        ///🍏 Apple Game = +{3}🎊 | -{4}💰
        ///🎲 Dice Game = +{5}🎊 | -{6}💰
        ///
        ///Do not play so much and safety first! 🧗‍♀️.
        /// </summary>
        public static string gameroomCommand {
            get {
                return ResourceManager.GetString("gameroomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameroom ⚽️.
        /// </summary>
        public static string gameroomCommandDescription {
            get {
                return ResourceManager.GetString("gameroomCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need more gold 💰.
        /// </summary>
        public static string goldNotEnough {
            get {
                return ResourceManager.GetString("goldNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈 Welcome to the world of Tamagotchi! 🌈
        ///Here you can make yourself a new virtual friend 🐩🐈🐈‍⬛🐕
        ///Be sure to keep track of your pet&apos;s progress:
        ///▫️ play different games with him ⚽️
        ///▫️feed yummy 🍕🍳🍫
        ///▫️ take care of him 🍼
        ///▫️ take care and just love 😻
        ///
        ///In the command menu you will find everything your pet needs 🌻
        ///Visit your pet more often, because he loves you too and will be very happy to take you for a walk 🤍❤️🤍
        ///
        ///FAQ:
        ///1. How does the 🏅 level accumulate?
        ///- 100 experience = 1 level. Exp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string helpCommand {
            get {
                return ResourceManager.GetString("helpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the game ❓.
        /// </summary>
        public static string helpCommandDescription {
            get {
                return ResourceManager.GetString("helpCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the pills 💊💊💊.
        /// </summary>
        public static string hospitalCommandCurePills {
            get {
                return ResourceManager.GetString("hospitalCommandCurePills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital 🏥.
        /// </summary>
        public static string hospitalCommandDescription {
            get {
                return ResourceManager.GetString("hospitalCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A healthy pet is the key to success 🏄🏄🏻‍♀️🏄
        ///Good job, your pet is full of energy: {0}% ❤️‍🔥.
        /// </summary>
        public static string hospitalCommandHighHp {
            get {
                return ResourceManager.GetString("hospitalCommandHighHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesus Christ! Your pet is one foot in the grave! ☠️
        ///Help him now! 🚑
        ///Health: {0}%.
        /// </summary>
        public static string hospitalCommandLowHp {
            get {
                return ResourceManager.GetString("hospitalCommandLowHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety first 🏥
        ///Do not forget feed your pet! 🤕
        ///Health is middle level: {0}%.
        /// </summary>
        public static string hospitalCommandMidHp {
            get {
                return ResourceManager.GetString("hospitalCommandMidHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😺 Get your own Tamagotchi.
        /// </summary>
        public static string InviteGlobalMultiplayerButton {
            get {
                return ResourceManager.GetString("InviteGlobalMultiplayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you don’t have your Tamagotchi yet 🐧.
        /// </summary>
        public static string InviteGlobalMultiplayerText {
            get {
                return ResourceManager.GetString("InviteGlobalMultiplayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐣 Become a friend for {0}.
        /// </summary>
        public static string InviteReferalMultiplayerButton {
            get {
                return ResourceManager.GetString("InviteReferalMultiplayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the kitchen 🥦
        ///🍕 Pet&apos;s satiety: {0}%
        ///💰 Gold: {1}
        ///
        ///Bread 🍞 = +50%🍕 |-30💰
        ///Apple 🍎 = +5%🍕 |-1💰
        ///Lollipop 🍭 = +1%🍕 |-0 💰
        ///Chocolate 🍫 = +2%🍕 |-0💰
        ///
        ///Don&apos;t forget feed him 🐣.
        /// </summary>
        public static string kitchenCommand {
            get {
                return ResourceManager.GetString("kitchenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen 🍽.
        /// </summary>
        public static string kitchenCommandDescription {
            get {
                return ResourceManager.GetString("kitchenCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language 🇺🇸 | język 🇵🇱 | мова 🇨🇷 | язык 🇷🇺.
        /// </summary>
        public static string languageCommandDescription {
            get {
                return ResourceManager.GetString("languageCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do with pet:
        ////pet - pet&apos;s status 🐱
        ////kitchen - feed your pet 🍕
        ////work - to earn more gold 💰
        ////reward - to earn daily bonus 🎁 
        ////sleep - bedroom 🧸
        ////gameroom entertainments 🎳
        ////ranks - see the best pets! 👑
        ////hospital - cure your pet 🏥
        ////bathroom - clean your pet 🛁
        ////referal - referral program 👩‍👩‍👧‍👦
        ////rename - to change name 🌀
        ///
        ///There will be more in future!
        ///Stay tuned! 💝.
        /// </summary>
        public static string menuCommand {
            get {
                return ResourceManager.GetString("menuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions with pet 🎒.
        /// </summary>
        public static string menuCommandDescription {
            get {
                return ResourceManager.GetString("menuCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To participate you must have a pet 🪿.
        /// </summary>
        public static string MPNoPetCallbackAlert {
            get {
                return ResourceManager.GetString("MPNoPetCallbackAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {8}, here is your pet
        ///
        ///🐱 &lt;b&gt;{0}&lt;/b&gt;
        ///💊 Health: {1}%
        ///🍕 Satiety: {2}%
        ///🛁 Hygiene: {3}%
        ///😴 Fatigue: {4}%
        ///🎊 Joy: {5}%
        ///
        ///🏅 {6} level
        ///💰 Gold: {7} 💴.
        /// </summary>
        public static string MultiplayerShowPet {
            get {
                return ResourceManager.GetString("MultiplayerShowPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to start a duel you need {2}💰gold
        ///You only have {1}💰.
        /// </summary>
        public static string NotEnoughGoldForDuel {
            get {
                return ResourceManager.GetString("NotEnoughGoldForDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To accept a duel you need {1}💰gold
        ///You only have {0}💰.
        /// </summary>
        public static string NotEnoughGoldForDuelCallback {
            get {
                return ResourceManager.GetString("NotEnoughGoldForDuelCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you don&apos;t have enough money ☠️.
        /// </summary>
        public static string NotEnoughGoldToResurrect {
            get {
                return ResourceManager.GetString("NotEnoughGoldToResurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ❌.
        /// </summary>
        public static string NoTextEmoji {
            get {
                return ResourceManager.GetString("NoTextEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a long search and a lot of money for detectives, the pet was found! 😺
        ///You asked for forgiveness for a long time and promised not to forget about your pet again 🐣
        ///You both reconciled 💕
        ///
        ////pet - check pet status.
        /// </summary>
        public static string PetCameBackText {
            get {
                return ResourceManager.GetString("PetCameBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///
        ///💊 HP: {1}%
        ///🍕 Satiety: {4}%
        ///🛁 Hygiene: {9}%
        ///😴 Fatigue: {5}%
        ///🎊 Joy level: {7}%
        ///
        ///💰 Gold: {8} 💴
        ///⚡️ Status: {6}
        ///🏅 &lt;b&gt;{3} level &lt;/b&gt;
        ///✨ &lt;i&gt;EXP: {2}/100&lt;/i&gt;
        ///
        ////gameroom - Play in Apple🍎
        ////reward - Get your daily reward 🎁.
        /// </summary>
        public static string petCommand {
            get {
                return ResourceManager.GetString("petCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet&apos;s status ❤️‍🩹.
        /// </summary>
        public static string petCommandDescription {
            get {
                return ResourceManager.GetString("petCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info 📋.
        /// </summary>
        public static string petCommandInlineBasicInfo {
            get {
                return ResourceManager.GetString("petCommandInlineBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra info 📝.
        /// </summary>
        public static string petCommandInlineExtraInfo {
            get {
                return ResourceManager.GetString("petCommandInlineExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///
        ///🎂 Date of birth: {1}
        ///👫 Referrals: {2}.
        /// </summary>
        public static string petCommandMoreInfo1 {
            get {
                return ResourceManager.GetString("petCommandMoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet has been cured on {0}% 🌡
        ///But joy decreased on {1}%.
        /// </summary>
        public static string PetCuringAnwserCallback {
            get {
                return ResourceManager.GetString("PetCuringAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet has satisfied hunger on {0}%.
        /// </summary>
        public static string PetFeedingAnwserCallback {
            get {
                return ResourceManager.GetString("PetFeedingAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hygiene +{0}%.
        /// </summary>
        public static string PetHygieneAnwserCallback {
            get {
                return ResourceManager.GetString("PetHygieneAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pet is clean enough 💦.
        /// </summary>
        public static string PetIsCleanEnoughAlert {
            get {
                return ResourceManager.GetString("PetIsCleanEnoughAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pet has already played enough ⛹️‍♀️.
        /// </summary>
        public static string PetIsFullOfJoyText {
            get {
                return ResourceManager.GetString("PetIsFullOfJoyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy increased by {0}% 🎊.
        /// </summary>
        public static string PetPlayingAnwserCallback {
            get {
                return ResourceManager.GetString("PetPlayingAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet is sleeping now 💤.
        /// </summary>
        public static string PetSleepingAlreadyAnwserCallback {
            get {
                return ResourceManager.GetString("PetSleepingAlreadyAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet doesn&apos;t want to sleep yet 🌞.
        /// </summary>
        public static string PetSleepingDoesntWantYetAnwserCallback {
            get {
                return ResourceManager.GetString("PetSleepingDoesntWantYetAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold +{1} 💰
        ///The pet is tired at +{0}% 😓
        ///Wait until the pet finishes work.
        /// </summary>
        public static string PetWorkingAnswerCallback {
            get {
                return ResourceManager.GetString("PetWorkingAnswerCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📛 Quit Mini-game.
        /// </summary>
        public static string quitCommandDescription {
            get {
                return ResourceManager.GetString("quitCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string quitText {
            get {
                return ResourceManager.GetString("quitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You went to watch the fireworks 🎇
        ///But the pet accidentally stepped into a puddle 💦
        ///
        ///
        ///+20% joy 🎊
        ///-10% hygiene 🛁
        ///
        ////pet - check pet&apos;s status.
        /// </summary>
        public static string RandomEventFireworks {
            get {
                return ResourceManager.GetString("RandomEventFireworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking with a pet in the city, you met an old friend of Lionko🦁
        ///
        ///+40% to joy 🎊
        ///+15 gold 💰 (borrowed from a friend)
        ///
        ////pet - check pet&apos;s status.
        /// </summary>
        public static string RandomEventFriendMet {
            get {
                return ResourceManager.GetString("RandomEventFriendMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌭 You were asked to rate a new hot dog recipe 🧑‍🍳
        ///
        ///+40 satiety🍕
        ///+20 gold💰
        ///
        ////pet - check pet&apos;s status.
        /// </summary>
        public static string RandomEventHotdog {
            get {
                return ResourceManager.GetString("RandomEventHotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You took a walk through the botanical garden 🌷🌷🌷
        ///🐱 I liked it very much, we will definitely come back here!
        ///
        ///+10% joy 🎊
        ///
        ////pet - check the status of the pet.
        /// </summary>
        public static string RandomEventNiceFlower {
            get {
                return ResourceManager.GetString("RandomEventNiceFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 You and your pet had a great time playing on the computer
        ///
        ///+30% joy 🎊
        ///
        ////pet - check the status of the pet.
        /// </summary>
        public static string RandomEventPlayComputerGames {
            get {
                return ResourceManager.GetString("RandomEventPlayComputerGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈 You saw the rainbow after the rain 🌦
        ///
        ///+10% joy 🎊
        ///
        ////pet - check pet&apos;s status.
        /// </summary>
        public static string RandomEventRainbow {
            get {
                return ResourceManager.GetString("RandomEventRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧑‍🌾Some passerby stepped on the pet&apos;s foot 🗣
        ///
        /// 👺-1% health
        /// 💊-10% joy🎊
        ///
        ////pet - check pet&apos;s status.
        /// </summary>
        public static string RandomEventStepOnFoot {
            get {
                return ResourceManager.GetString("RandomEventStepOnFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️‍🔥Help your pet urgently!
        ///😾: my tummy hurts very much...
        ///
        ///-5% health 💊
        ///-15% satiety 🍕
        ///
        ////hospital - you have to run to the clinic!.
        /// </summary>
        public static string RandomEventStomachache {
            get {
                return ResourceManager.GetString("RandomEventStomachache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱: Delicious watermelon, I want more 🍉
        ///
        ///+15% satiety 🍕
        ///
        ////pet - check the status of the pet.
        /// </summary>
        public static string RandomEventWatermelon {
            get {
                return ResourceManager.GetString("RandomEventWatermelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈⭐️ Top 10 Experience⭐️🌈.
        /// </summary>
        public static string ranksCommand {
            get {
                return ResourceManager.GetString("ranksCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍎⭐️ Top 10 in apples game ⭐️🍎.
        /// </summary>
        public static string ranksCommandApples {
            get {
                return ResourceManager.GetString("ranksCommandApples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating 🏆.
        /// </summary>
        public static string ranksCommandDescription {
            get {
                return ResourceManager.GetString("ranksCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰⭐️ Top 10 in gold ⭐️💰.
        /// </summary>
        public static string ranksCommandGold {
            get {
                return ResourceManager.GetString("ranksCommandGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍎Apples.
        /// </summary>
        public static string ranksCommandInlineApples {
            get {
                return ResourceManager.GetString("ranksCommandInlineApples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Gold.
        /// </summary>
        public static string ranksCommandInlineGold {
            get {
                return ResourceManager.GetString("ranksCommandInlineGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏅Experience.
        /// </summary>
        public static string ranksCommandInlineLevel {
            get {
                return ResourceManager.GetString("ranksCommandInlineLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking together is much more fun, right? 👯‍♀️
        ///Invite your friends to hang out using your referral link and get prizes for it! 🎁
        ///
        ///🚦A friend must create his own Tamagotchi for the prizes to come to your account 🚦
        ///
        ///🤼‍♀️ You have referrals: {0}
        ///Gold earned via referral: {1}💰
        ///
        ///Your referral link:
        ///{2}.
        /// </summary>
        public static string referalCommand {
            get {
                return ResourceManager.GetString("referalCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👬 Prizes for a friend.
        /// </summary>
        public static string referalCommandDescription {
            get {
                return ResourceManager.GetString("referalCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} apples left.
        /// </summary>
        public static string remainingApplesText {
            get {
                return ResourceManager.GetString("remainingApplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😺: You&apos;ve come back!
        ///I&apos;ve missed you so much!
        ///I want to eat 🌭 and play with you 🪁
        ///
        ////kitchen to feed 🍩
        ////gameroom for games 🏓.
        /// </summary>
        public static string ReminderNotifyText1 {
            get {
                return ResourceManager.GetString("ReminderNotifyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱: Waiting for you here, come back
        ///
        ////kitchen to feed 🍩
        ////gameroom for games 🏓.
        /// </summary>
        public static string ReminderNotifyText2 {
            get {
                return ResourceManager.GetString("ReminderNotifyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱: Sadness to be alone...
        ///
        ////kitchen to feed 🍩
        ////gameroom for games 🏓.
        /// </summary>
        public static string ReminderNotifyText3 {
            get {
                return ResourceManager.GetString("ReminderNotifyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to do this.
        /// </summary>
        public static string renameBannedCommand {
            get {
                return ResourceManager.GetString("renameBannedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new name for pet 🗯️.
        /// </summary>
        public static string renameCommand {
            get {
                return ResourceManager.GetString("renameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name ✏️.
        /// </summary>
        public static string renameCommandDescription {
            get {
                return ResourceManager.GetString("renameCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped pet {0} 💔.
        /// </summary>
        public static string restartCommand {
            get {
                return ResourceManager.GetString("restartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ⁉️.
        /// </summary>
        public static string ResurrectNoText {
            get {
                return ResourceManager.GetString("ResurrectNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (-1000 💰).
        /// </summary>
        public static string ResurrectYesText {
            get {
                return ResourceManager.GetString("ResurrectYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a daily reward waiting for you! 💸
        ///Take it soon! 🎁.
        /// </summary>
        public static string rewardCommand {
            get {
                return ResourceManager.GetString("rewardCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already got your daily reward today 🫶🏻.
        /// </summary>
        public static string rewardCommandDailyRewardGotten {
            get {
                return ResourceManager.GetString("rewardCommandDailyRewardGotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until the next award: {0} ⏱.
        /// </summary>
        public static string rewardCommandDailyRewardInlineShowTime {
            get {
                return ResourceManager.GetString("rewardCommandDailyRewardInlineShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward 🎁.
        /// </summary>
        public static string rewardCommandDescription {
            get {
                return ResourceManager.GetString("rewardCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily 🎉(+100💰).
        /// </summary>
        public static string rewardCommandInlineDailyReward {
            get {
                return ResourceManager.GetString("rewardCommandInlineDailyReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎁 Come on for your daily bonus 🎉
        ////reward 🎁.
        /// </summary>
        public static string rewardNotification {
            get {
                return ResourceManager.GetString("rewardNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦁 Show your pet.
        /// </summary>
        public static string ShowPetMPCommand {
            get {
                return ResourceManager.GetString("ShowPetMPCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello everyone in the {0} chat!
        ///Bot 🐾 Tamagotchi | Virtual Pet 🐾 provides the opportunity to have your own pet directly in Telegram
        ///
        ///Available commands in chat:
        ////show_pet - show your pet.
        /// </summary>
        public static string ShowWelcomeMessageMultiplayer {
            get {
                return ResourceManager.GetString("ShowWelcomeMessageMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///😴 Fatigue: {1}%
        ///⚡️ Status: {2}.
        /// </summary>
        public static string sleepCommand {
            get {
                return ResourceManager.GetString("sleepCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom 🛏.
        /// </summary>
        public static string sleepCommandDescription {
            get {
                return ResourceManager.GetString("sleepCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put to sleep 🛌.
        /// </summary>
        public static string sleepCommandInlinePutToSleep {
            get {
                return ResourceManager.GetString("sleepCommandInlinePutToSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains to sleep: {0} 🌚.
        /// </summary>
        public static string sleepCommandInlineShowTime {
            get {
                return ResourceManager.GetString("sleepCommandInlineShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a pet battle! ⚔️.
        /// </summary>
        public static string StartDuelMPCommand {
            get {
                return ResourceManager.GetString("StartDuelMPCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string statisticsText {
            get {
                return ResourceManager.GetString("statisticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test value.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Add to new chat.
        /// </summary>
        public static string ToAddToNewGroupReferalCommand {
            get {
                return ResourceManager.GetString("ToAddToNewGroupReferalCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet is good now. Enough to eat 🤢.
        /// </summary>
        public static string tooManyStarvingCommand {
            get {
                return ResourceManager.GetString("tooManyStarvingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet is too tired, he should sleep 💤.
        /// </summary>
        public static string tooTiredText {
            get {
                return ResourceManager.GetString("tooTiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To resurrect your pet? 🧬.
        /// </summary>
        public static string ToResurrectQuestion {
            get {
                return ResourceManager.GetString("ToResurrectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📩 Share link.
        /// </summary>
        public static string ToShareReferalCommand {
            get {
                return ResourceManager.GetString("ToShareReferalCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Welcome to Tamagotchi Bot! Here you can raise your own virtual pet, play with him and compete with another players 🎮
        ///Let&apos;s start!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go! 😻.
        /// </summary>
        public static string WelcomeStatusButton {
            get {
                return ResourceManager.GetString("WelcomeStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what your pet will be doing 💡
        ///
        ///😴 Fatigue: {2}%
        ///
        ///Programing 💻 -{0} minutes ⌛️, +{1} golds 💰.
        /// </summary>
        public static string workCommand {
            get {
                return ResourceManager.GetString("workCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs 💰.
        /// </summary>
        public static string workCommandDescription {
            get {
                return ResourceManager.GetString("workCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program 💻.
        /// </summary>
        public static string workCommandInlinePC {
            get {
                return ResourceManager.GetString("workCommandInlinePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains to work: {0} ⏱.
        /// </summary>
        public static string workCommandInlineShowTime {
            get {
                return ResourceManager.GetString("workCommandInlineShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet is working now 👩‍💻.
        /// </summary>
        public static string workCommandPCWorking {
            get {
                return ResourceManager.GetString("workCommandPCWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes ✅.
        /// </summary>
        public static string YesTextEmoji {
            get {
                return ResourceManager.GetString("YesTextEmoji", resourceCulture);
            }
        }
    }
}
