//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TamagotchiBot.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new language 🇺🇸
        ///Выберы новую мову 🇨🇷
        ///Wybierz nowy język 🇵🇱
        ///Выбери новый язык 🇷🇺.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧸 First of all you need to name your new friend
        ///Just type it here.
        /// </summary>
        public static string ChooseName {
            get {
                return ResourceManager.GetString("ChooseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language was set to English 🇺🇸.
        /// </summary>
        public static string ConfirmedLanguage {
            get {
                return ResourceManager.GetString("ConfirmedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧃 Nice!
        ///Your pet is waiting for you 🐱
        ///Do not forget feed and wash him, play a games and just love ☺️.
        /// </summary>
        public static string ConfirmedName {
            get {
                return ResourceManager.GetString("ConfirmedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active 🌞.
        /// </summary>
        public static string CurrentStatusActive {
            get {
                return ResourceManager.GetString("CurrentStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleeping 🌙.
        /// </summary>
        public static string CurrentStatusSleeping {
            get {
                return ResourceManager.GetString("CurrentStatusSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not come in: pet is sleeping 🌙.
        /// </summary>
        public static string denyAccessSleeping {
            get {
                return ResourceManager.GetString("denyAccessSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In developing, wait for next update 👾.
        /// </summary>
        public static string DevelopWarning {
            get {
                return ResourceManager.GetString("DevelopWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fresh.
        /// </summary>
        public static string FatigueFresh {
            get {
                return ResourceManager.GetString("FatigueFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rested.
        /// </summary>
        public static string FatigueRested {
            get {
                return ResourceManager.GetString("FatigueRested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleepy.
        /// </summary>
        public static string FatigueSleepy {
            get {
                return ResourceManager.GetString("FatigueSleepy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slightly tired.
        /// </summary>
        public static string FatigueSlightlyTired {
            get {
                return ResourceManager.GetString("FatigueSlightlyTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tired.
        /// </summary>
        public static string FatigueTired {
            get {
                return ResourceManager.GetString("FatigueTired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the gameroom
        ///
        ///⚽️ Fatigue level: {0}
        ///🎊 Joy level: {1}%
        ///
        ///Do not play so much and safety first! 🧗‍♀️.
        /// </summary>
        public static string gameroomCommand {
            get {
                return ResourceManager.GetString("gameroomCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚽️ Gameroom.
        /// </summary>
        public static string gameroomCommandDescription {
            get {
                return ResourceManager.GetString("gameroomCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in the kitchen 🥦
        ///🍕 Pet&apos;s hunger: {0}%
        ///
        ///Don&apos;t forget feed him 🐣.
        /// </summary>
        public static string kitchenCommand {
            get {
                return ResourceManager.GetString("kitchenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitchen 🍽.
        /// </summary>
        public static string kitchenCommandDescription {
            get {
                return ResourceManager.GetString("kitchenCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language 🇺🇸 | język 🇵🇱 | мова 🇨🇷 | язык 🇷🇺.
        /// </summary>
        public static string languageCommandDescription {
            get {
                return ResourceManager.GetString("languageCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///💊 HP: {1}%
        ///🍕 Hunger: {4}%
        ///😴 Fatigue: {5}
        ///🎊 Joy level: {7}%
        ///⚡️ Status: {6}
        ///🏅 EXP: {2} | {3} level ✨.
        /// </summary>
        public static string petCommand {
            get {
                return ResourceManager.GetString("petCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pet&apos;s status ❤️‍🩹.
        /// </summary>
        public static string petCommandDescription {
            get {
                return ResourceManager.GetString("petCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info 📋.
        /// </summary>
        public static string petCommandInlineBasicInfo {
            get {
                return ResourceManager.GetString("petCommandInlineBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra info 📝.
        /// </summary>
        public static string petCommandInlineExtraInfo {
            get {
                return ResourceManager.GetString("petCommandInlineExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///🎂 Birth date: {1}.
        /// </summary>
        public static string petCommandMoreInfo1 {
            get {
                return ResourceManager.GetString("petCommandMoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet has satisfied hunger on {0}%.
        /// </summary>
        public static string PetFeedingAnwserCallback {
            get {
                return ResourceManager.GetString("PetFeedingAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet&apos;s fatigue increased in {0}%.
        /// </summary>
        public static string PetPlayingAnwserCallback {
            get {
                return ResourceManager.GetString("PetPlayingAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet is sleeping now 💤.
        /// </summary>
        public static string PetSleepingAlreadyAnwserCallback {
            get {
                return ResourceManager.GetString("PetSleepingAlreadyAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet doesn&apos;t want to sleep yet.
        /// </summary>
        public static string PetSleepingDoesntWantYetAnwserCallback {
            get {
                return ResourceManager.GetString("PetSleepingDoesntWantYetAnwserCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌈⭐️ Top 10 Levels ⭐️.
        /// </summary>
        public static string ranksCommand {
            get {
                return ResourceManager.GetString("ranksCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating 🏆.
        /// </summary>
        public static string ranksCommandDescription {
            get {
                return ResourceManager.GetString("ranksCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///😴 Fatigue: {1}%
        ///⚡️ Status: {2}.
        /// </summary>
        public static string sleepCommand {
            get {
                return ResourceManager.GetString("sleepCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom 🛏.
        /// </summary>
        public static string sleepCommandDescription {
            get {
                return ResourceManager.GetString("sleepCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put to sleep 🛌.
        /// </summary>
        public static string sleepCommandInlinePutToSleep {
            get {
                return ResourceManager.GetString("sleepCommandInlinePutToSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains to sleep: {0} 🌚.
        /// </summary>
        public static string sleepCommandInlineShowTime {
            get {
                return ResourceManager.GetString("sleepCommandInlineShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test value.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Welcome to Tamagotchi Bot! Here you can raise your own virtual pet, play with him and compete with another players 🎮
        ///Let&apos;s start? 
        ////start.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
