//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TamagotchiBot.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new language 🇺🇸
        ///Выберы новую мову 🇰🇵
        ///Wybierz nowy język 🇵🇱
        ///Выбери новый язык 🇷🇺.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧸 First of all you need to name your new friend
        ///Just type it here.
        /// </summary>
        public static string ChooseName {
            get {
                return ResourceManager.GetString("ChooseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language was set to English 🇺🇸.
        /// </summary>
        public static string ConfirmedLanguage {
            get {
                return ResourceManager.GetString("ConfirmedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧃 Nice!
        ///Your pet is waiting for you 🐱
        ///Do not forget feed and wash him, play a games and just love ☺️.
        /// </summary>
        public static string ConfirmedName {
            get {
                return ResourceManager.GetString("ConfirmedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In developing, wait for next update 👾.
        /// </summary>
        public static string DevelopWarning {
            get {
                return ResourceManager.GetString("DevelopWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///💊 HP: {1}
        ///🏅 EXP: {2} | {3} level ✨.
        /// </summary>
        public static string petCommand {
            get {
                return ResourceManager.GetString("petCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info 📋.
        /// </summary>
        public static string petCommandInlineBasicInfo {
            get {
                return ResourceManager.GetString("petCommandInlineBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra info 📝.
        /// </summary>
        public static string petCommandInlineExtraInfo {
            get {
                return ResourceManager.GetString("petCommandInlineExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐱 {0}
        ///🎂 Birth date: {1}.
        /// </summary>
        public static string petCommandMoreInfo1 {
            get {
                return ResourceManager.GetString("petCommandMoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test value.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Welcome to Tamagotchi Bot! Here you can raise your own virtual pet, play with him and compete with another players 🎮
        ///Let&apos;s start?.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
